### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by risharde** [harperreed/google-home-notifier-python#8]
Getting the following error on my Raspberry PI after following instructions on installing, any ideas?

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import pychromecast
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/__init__.py", line 15, in <module>
    from .discovery import discover_chromecasts, start_discovery, stop_discovery
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/discovery.py", line 5, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 175
    def current_time_millis() -> float:
                              ^
SyntaxError: invalid syntax

**Comment by Volting** [comment]
Use Python 3
